image: debian/stable
packages:
  - curl
sources:
  - https://git.sr.ht/~wezm/pitemp
tasks:
  - install: curl https://sh.rustup.rs -sSf | sh -s -- -y
  - test: |
      cd pitemp
      PATH="$HOME/.cargo/bin:$PATH" cargo test
