#!/bin/sh

set -e

# Requires arm-linux-gnueabihf-binutils Arch package installed

TARGET=arm-unknown-linux-gnueabihf

cargo build --release --target=$TARGET
arm-linux-gnueabihf-strip target/$TARGET/release/pitemp
tar zcvf pitemp-v0.X.0-$TARGET.tar.gz -C target/$TARGET/release pitemp
