#!/bin/sh

set -e

# Requires cross https://github.com/rust-embedded/cross
# and arm-linux-gnueabihf-binutils Arch package installed

cross build --target=arm-unknown-linux-gnueabi --release
arm-linux-gnueabihf-strip target/arm-unknown-linux-gnueabi/release/pitemp
tar zcvf pitemp-v0.X.0-arm-linux-gnueabi.tar.gz -C target/arm-unknown-linux-gnueabi/release pitemp
